[Plugin-1730] Adding XLS UI elements for ftp source
data-integrations/ftp-plugins pull request #48
Opened 2024-01-31 22:01 UTC by psainics

## Adding XLS UI elements for ftp source

Jira : [Plugin-1730](https://cdap.atlassian.net/browse/PLUGIN-1730)

### Description
This PR adds UI element required for XLS Support in `FTP Source`.
Ref : XLS Support PR https://github.com/cdapio/hydrator-plugins/pull/1835

### Added Fields 
- Sample Size
- Override
- Terminate If Empty Row
- Select Sheet Using
- Sheet Value

A filter is used to show XLS specific values  `Terminate If Empty Row` , `Select Sheet Using`, `Sheet Value` only when format `XLS` is selected.

### Preview
![image](https://github.com/cloudsufi/ftp-plugins/assets/122770897/a438bd23-9bb8-41dd-807c-7cccb166065e)

2024-03-05 09:34 UTC, DJSagarAhire reviewed
Most comments from https://github.com/data-integrations/google-cloud/pull/1368 are also applicable here. Looks good apart from those.

2025-04-28 05:29 UTC, vikasrathee-cs commented
> Most comments from [data-integrations/google-cloud#1368](https://github.com/data-integrations/google-cloud/pull/1368) are also applicable here. Looks good apart from those.

Changes done as per comments

2025-04-28 06:59 UTC, itsankit-google commented on widgets/FTPSource-batchsource.json
> +          "label": "Terminate If Empty Row",
this sounds a bit unclear and technical for a toggle label:

some suggestions:

- `Stop Reading at First Empty Row`
- `Stop on First Empty Row`
- `Terminate Reading After Empty Row`

2025-04-28 07:30 UTC, vikasrathee-cs commented on widgets/FTPSource-batchsource.json
> +          "label": "Terminate If Empty Row",
Took reference from this: https://github.com/cdapio/hydrator-plugins/blob/f6363b0d4bf7e753c11f946c3594549f0acc4104/core-plugins/widgets/Excel-batchsource.json#L100

2025-04-30 10:47 UTC, itsankit-google commented on widgets/FTPSource-batchsource.json
> +          "label": "Terminate If Empty Row",
I think we should change at both places then to make it consistent and human readable everywhere.

2025-05-01 09:50 UTC, itsankit-google approved these changes

2025-05-01 09:51 UTC, itsankit-google requested changes
please fix unit test build and squash commits

2025-05-01 10:08 UTC, psainics commented
> please fix unit test build and squash commits

https://github.com/data-integrations/ftp-plugins/pull/68

2025-05-01 10:33 UTC, itsankit-google approved these changes

2025-05-02 02:50 UTC, merged